import{a as b,S as w,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const S="https://pixabay.com/api/",v="24246852-77467cbf1dd5333394cba3aaf",q=15;async function P(r,o){return(await b.get(S,{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:q}})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),p=document.querySelector(".load-more-btn");let B=new w(".gallery a",{captionsData:"alt",captionDelay:250});function E(r){const o=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:t,views:a,comments:h,downloads:L})=>`
      <li class="gallery-item-wrapper">
        <a class="gallery-image-wrapper" href="${i}">
          <img class="gallery-image" src="${s}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item">Likes<span class="info-item-numbers">${t}</span></p>
          <p class="info-item">Views<span class="info-item-numbers">${a}</span></p>
          <p class="info-item">Comments<span class="info-item-numbers">${h}</span></p>
          <p class="info-item">Downloads<span class="info-item-numbers">${L}</span></p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",o),B.refresh()}function M(){m.innerHTML=""}function y(){f.classList.remove("hidden")}function $(){f.classList.add("hidden")}function R(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}const A=document.querySelector(".form"),O=document.querySelector(".form-input"),I=document.querySelector(".load-more-btn");let l="",n=1,u=0;A.addEventListener("submit",async r=>{if(r.preventDefault(),l=O.value.trim(),l===""){c.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}n=1,M(),y(),await g()});I.addEventListener("click",async()=>{n++,await g()});async function g(){try{y();const r=await P(l,n),{hits:o,totalHits:s}=r;if(o.length===0&&n===1){c.error({message:"Sorry, no images found."}),d();return}E(o),u=Math.ceil(s/15),n<u?R():(d(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),n>1&&T()}catch(r){console.error(r),c.error({message:"Something went wrong. Try again.",position:"topRight"})}finally{$()}}function T(){const{height:r}=document.querySelector(".gallery-item-wrapper").getBoundingClientRect();window.scrollBy({top:r*3,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
